<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Блог обо всем</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="../../../styles/gate.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="header row justify-content-between align-items-center">
        <h1 class="col-3">Блог обо всем</h1>
        <? if ($role == ADMIN_ROLE): ?>
            <div class="col-2">
                <a href="user/admin" class="cabinet">Админка</a>
            </div>
        <? endif;?>
        <div class="col-2">
            <a href="http://week5-eloquent/blog" class="blog">В блог</a>
        </div>
        <form action="/user/logout" class="col-1">
            <input type="submit" value="Выйти" class="btn btn-danger">
        </form>
    </div>
    <div class="row">
        <table class="col align-self-center">
            <th>ID</th>
            <th>Имя</th>
            <th>Почта</th>
            <th>Роль</th>
            <th>Аватар</th>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td><b><?=$user->id?></b></td>
                    <td><?=$user->name?></td>
                    <td><?=$user->email?></td>
                    <td><?=$user->userRole?></td>
                    <td><img class="ava" src=<?=$user->avatar?>></td>
                </tr>
            <? endforeach; ?>
        </table>
    </div>

    <hr>
    <div class="row align-items-start justify-content-center">
        <div class="col-4">
            <h3>Добавить нового пользователя:</h3>
            <form action="/user/new" method="post">
                <label for="InputEmail" class="form-label">Email:</label>
                <input type="email" name="email" class="form-control" id="InputEmail">

                <label for="InputName" class="form-label">Имя:</label>
                <input type="text" name="name" class="form-control" id="InputName">

                <label for="InputName" class="form-label">Пароль:</label>
                <input type="password" name="password" class="form-control" id="InputPass" aria-describedby="passHelp1">
                <br>
                <input type="submit" class="btn btn-primary" value="Добавить нового пользователя">
            </form>
        </div>
        <div class="col-6">
            <h3>Изменить данные существующего пользователя:</h3>
            <form action="/user/change" method="post">
                <label for="InputId" class="form-label">Id:</label>
                <input type="text" name="id" class="form-control" id="InputId" aria-describedby="Help1">
                <div id="Help1" class="form-text">Номер пользователя из таблицы выше</div>

                <label for="InputEmail" class="form-label">Email:</label>
                <input type="email" name="email" class="form-control" id="InputEmail">

                <label for="InputName" class="form-label">Имя:</label>
                <input type="text" name="name" class="form-control" id="InputName">

                <label for="InputId" class="form-label">Аватар:</label>
                <input type="text" name="avatar" class="form-control" id="InputId" aria-describedby="Help2">
                <div id="Help2" class="form-text">Только прямая ссылка</div>

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="role" id="inlineRadio1" value="user">
                    <label class="form-check-label" for="inlineRadio1">Роль 1 (обычный юзер)</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="role" id="inlineRadio2" value="admin">
                    <label class="form-check-label" for="inlineRadio2">Роль 2 (админ)</label>
                </div>
                <br>
                <br>
                <input type="submit" class="btn btn-primary" value="Изменить">
            </form>
        </div>
    </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>
